package com.yts.revaux.ntquote.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NtProjectApprovalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtProjectApprovalAllPropertiesEquals(NtProjectApproval expected, NtProjectApproval actual) {
        assertNtProjectApprovalAutoGeneratedPropertiesEquals(expected, actual);
        assertNtProjectApprovalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtProjectApprovalAllUpdatablePropertiesEquals(NtProjectApproval expected, NtProjectApproval actual) {
        assertNtProjectApprovalUpdatableFieldsEquals(expected, actual);
        assertNtProjectApprovalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtProjectApprovalAutoGeneratedPropertiesEquals(NtProjectApproval expected, NtProjectApproval actual) {
        assertThat(expected)
            .as("Verify NtProjectApproval auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtProjectApprovalUpdatableFieldsEquals(NtProjectApproval expected, NtProjectApproval actual) {
        assertThat(expected)
            .as("Verify NtProjectApproval relevant properties")
            .satisfies(e -> assertThat(e.getSrNo()).as("check srNo").isEqualTo(actual.getSrNo()))
            .satisfies(e -> assertThat(e.getUid()).as("check uid").isEqualTo(actual.getUid()))
            .satisfies(e -> assertThat(e.getApprovedBy()).as("check approvedBy").isEqualTo(actual.getApprovedBy()))
            .satisfies(e -> assertThat(e.getApprovalDate()).as("check approvalDate").isEqualTo(actual.getApprovalDate()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedDate()).as("check updatedDate").isEqualTo(actual.getUpdatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtProjectApprovalUpdatableRelationshipsEquals(NtProjectApproval expected, NtProjectApproval actual) {
        assertThat(expected)
            .as("Verify NtProjectApproval relationships")
            .satisfies(e -> assertThat(e.getNtQuote()).as("check ntQuote").isEqualTo(actual.getNtQuote()));
    }
}
