package com.yts.revaux.ntquote.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NtQuoteCustomerPoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteCustomerPoAllPropertiesEquals(NtQuoteCustomerPo expected, NtQuoteCustomerPo actual) {
        assertNtQuoteCustomerPoAutoGeneratedPropertiesEquals(expected, actual);
        assertNtQuoteCustomerPoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteCustomerPoAllUpdatablePropertiesEquals(NtQuoteCustomerPo expected, NtQuoteCustomerPo actual) {
        assertNtQuoteCustomerPoUpdatableFieldsEquals(expected, actual);
        assertNtQuoteCustomerPoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteCustomerPoAutoGeneratedPropertiesEquals(NtQuoteCustomerPo expected, NtQuoteCustomerPo actual) {
        assertThat(expected)
            .as("Verify NtQuoteCustomerPo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteCustomerPoUpdatableFieldsEquals(NtQuoteCustomerPo expected, NtQuoteCustomerPo actual) {
        assertThat(expected)
            .as("Verify NtQuoteCustomerPo relevant properties")
            .satisfies(e -> assertThat(e.getSrNo()).as("check srNo").isEqualTo(actual.getSrNo()))
            .satisfies(e -> assertThat(e.getUid()).as("check uid").isEqualTo(actual.getUid()))
            .satisfies(e -> assertThat(e.getCustomerName()).as("check customerName").isEqualTo(actual.getCustomerName()))
            .satisfies(e -> assertThat(e.getQuoteDate()).as("check quoteDate").isEqualTo(actual.getQuoteDate()))
            .satisfies(e -> assertThat(e.getFileName()).as("check fileName").isEqualTo(actual.getFileName()))
            .satisfies(e -> assertThat(e.getCountry()).as("check country").isEqualTo(actual.getCountry()))
            .satisfies(e -> assertThat(e.getBrowse()).as("check browse").isEqualTo(actual.getBrowse()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedDate()).as("check updatedDate").isEqualTo(actual.getUpdatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteCustomerPoUpdatableRelationshipsEquals(NtQuoteCustomerPo expected, NtQuoteCustomerPo actual) {
        assertThat(expected)
            .as("Verify NtQuoteCustomerPo relationships")
            .satisfies(e -> assertThat(e.getNtQuote()).as("check ntQuote").isEqualTo(actual.getNtQuote()));
    }
}
