package com.yts.revaux.ntquote.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NtQuoteTermsConditionsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteTermsConditionsAllPropertiesEquals(NtQuoteTermsConditions expected, NtQuoteTermsConditions actual) {
        assertNtQuoteTermsConditionsAutoGeneratedPropertiesEquals(expected, actual);
        assertNtQuoteTermsConditionsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteTermsConditionsAllUpdatablePropertiesEquals(
        NtQuoteTermsConditions expected,
        NtQuoteTermsConditions actual
    ) {
        assertNtQuoteTermsConditionsUpdatableFieldsEquals(expected, actual);
        assertNtQuoteTermsConditionsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteTermsConditionsAutoGeneratedPropertiesEquals(
        NtQuoteTermsConditions expected,
        NtQuoteTermsConditions actual
    ) {
        assertThat(expected)
            .as("Verify NtQuoteTermsConditions auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteTermsConditionsUpdatableFieldsEquals(NtQuoteTermsConditions expected, NtQuoteTermsConditions actual) {
        assertThat(expected)
            .as("Verify NtQuoteTermsConditions relevant properties")
            .satisfies(e -> assertThat(e.getSrNo()).as("check srNo").isEqualTo(actual.getSrNo()))
            .satisfies(e -> assertThat(e.getUid()).as("check uid").isEqualTo(actual.getUid()))
            .satisfies(e -> assertThat(e.getTermsConditions()).as("check termsConditions").isEqualTo(actual.getTermsConditions()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getUpdatedBy()).as("check updatedBy").isEqualTo(actual.getUpdatedBy()))
            .satisfies(e -> assertThat(e.getUpdatedDate()).as("check updatedDate").isEqualTo(actual.getUpdatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNtQuoteTermsConditionsUpdatableRelationshipsEquals(
        NtQuoteTermsConditions expected,
        NtQuoteTermsConditions actual
    ) {
        assertThat(expected)
            .as("Verify NtQuoteTermsConditions relationships")
            .satisfies(e -> assertThat(e.getNtQuote()).as("check ntQuote").isEqualTo(actual.getNtQuote()));
    }
}
